import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  IsEnum,
  IsNumber,
  IsOptional,
  IsString,
  IsUUID,
  Max,
  Min,
} from 'class-validator';
import { MatchStatus, UrgencyLevel } from '../../../common/enums';

export class CreateMatchDto {
  @ApiProperty({ example: '9e8f2494-6ef9-47d8-807e-3a1204f403af' })
  @IsUUID()
  patientId!: string;

  @ApiProperty({ example: '311a4214-f5ee-4e03-a942-7ef7ebcfd9fe' })
  @IsUUID()
  donorId!: string;

  @ApiPropertyOptional({ enum: MatchStatus, default: MatchStatus.PENDING })
  @IsOptional()
  @IsEnum(MatchStatus)
  status?: MatchStatus;

  @ApiPropertyOptional({ example: 78 })
  @IsOptional()
  @IsNumber()
  @Min(0)
  @Max(100)
  compatibilityScore?: number;

  @ApiPropertyOptional({ example: 'ABO match confirmed. HLA pending.' })
  @IsOptional()
  @IsString()
  matchReason?: string;

  @ApiPropertyOptional({ enum: UrgencyLevel })
  @IsOptional()
  @IsEnum(UrgencyLevel)
  urgencyLevel?: UrgencyLevel;

  @ApiPropertyOptional({ example: 'Initial manual review generated by coordinator.' })
  @IsOptional()
  @IsString()
  reviewNotes?: string;

  @ApiPropertyOptional({ example: '35c2b376-4c58-45c6-b467-4fea96eb2f7e' })
  @IsOptional()
  @IsUUID()
  reviewedByCoordinatorId?: string;
}
